quarkus:
  http:
    auth:
      basic: true
  datasource:
    db-kind: postgresql
    username: quarkusodata
    password: quarkusodata
    reactive:
      url: postgresql://localhost:5432/reactodata
reactodata:
  schema:
    create: true